### ISSUE TITLE
多设备同步配置问题

### ISSUE THREAD

**Issue by commis** [hoothin/SearchJumper#177]
多台PC使用和手机均使用Firefox作为主浏览器，该插件在一台设备上配置完成后，不方便将配置同步到其他设备上，能够在配置页面提供可配置项自动同步在多设备之间同步。

增加 WebDev 网盘地址，访问用户名和密码，数据存储在用户自己的网盘上，安全由用户自己负责，也不会存在数据隐私问题。

希望能增加此功能。

**Comment by hoothin** [comment]
导出设置-右边第二个就是 Webdav 功能。你说的具体是什么意思？

**Comment by commis** [comment]
第一次使用，没发现右边还有菜单。
Webdav服务器使用了Nextcloud内置的，其他的应用可以正常访问webdav，但就是该插件无法访问，是不支持吗？

**Comment by hoothin** [comment]
脚本版无法跨域，需要自己配置 webdav 服务器返回头。说明里都写了。
或者也可以换插件版。

**Comment by commis** [comment]
参考README搭建webdav服务，webdav的版本是v5.4.0，配置如下：
```yml
address: 0.0.0.0
port: 6065
debug: true
directory: /data/webdav
permissions: R
cors:
  enabled: true
  credentials: true
  allowed_headers:
    - Depth,Authorization
  allowed_hosts:
    - https://search.hoothin.com
    - https://hoothin.github.io
  allowed_methods:
    - GET,POST,OPTIONS
  exposed_headers:
    - Content-Length
    - Content-Range
users:
  - username: test
    password: xxxxxx
    permissions: CRUD
```
通过浏览器浏览和Postman发送PROPFIND请求均正常，但是使用插件配置webdav同步参数，保存就是就是不行，浏览器debug窗口响应：
脚本无法获取响应主体（原因：CORS Missing Allow Origin）

插件中webdav配置：

地址：http://107.174.95.154:6065/
用户名和密码使用服务器端配置的参数。
