### ISSUE TITLE
两个奇怪的现象

### ISSUE THREAD

**Issue by wordpure** [hoothin/SearchJumper#30]
1. 添加表单的 textarea 可以拖曳到表单外。
	
	![图片](https://user-images.githubusercontent.com/68013962/198837143-25d4ab4e-9a8e-4e84-989c-9ab58c0fe76f.png)
2. 「常规位置 - 工具栏位置 - 缩放工具栏」的文本输入框，似乎是实时保存的，输入过程会被强制改为最小值和最大值😂
	
	![输入不受控制](https://user-images.githubusercontent.com/68013962/198839529-30011c68-a811-4f05-a4b2-a36dd74d973c.gif)

**Comment by wordpure** [comment]
顺便提两个关于样式的功能请求。

1. 希望地址、图标字段可以完整展示两行文本。
	有半行没展示出来就很别扭😂

	> 1. ![图片](https://user-images.githubusercontent.com/68013962/198837143-25d4ab4e-9a8e-4e84-989c-9ab58c0fe76f.png)
2. 希望搜索酱能支持深色模式。

**Comment by hoothin** [comment]
感谢建议，css太庞大了，深色模式可能不大可行，但几个窗体添加深色模式没问题。

**Comment by wordpure** [comment]
感谢，感知最明显的就是添加表单这几个窗体了，能适配基本就够用了

**Comment by hoothin** [comment]
几个窗体已经适配暗黑模式了

**Comment by wordpure** [comment]
感谢大佬。

冒昧问下，工具栏、站点列表可否也适配下深色模式？

![图片](https://user-images.githubusercontent.com/68013962/199164913-b2cc286a-02a6-4309-9a8c-766b8a69c262.png)

![图片](https://user-images.githubusercontent.com/68013962/199164896-f44da31f-4072-4241-aa1c-96fd0b8002e2.png)

主要就是下列选择器的背景色，以及 `.search-jumper-word:hover` 的 text-shadow。

```css
    .search-jumper-type,
    .search-jumper-logo,
    .search-jumper-historylist,
    .search-jumper-word:hover,
    #search-jumper .sitelist > .sitelistCon,
    #search-jumper .sitelist > .sitelistCon > p,
    #search-jumper .sitelist > .sitelistCon > div:hover

    a.search-jumper-word,
    a.search-jumper-word > span,
    .search-jumper-tips
```

**Comment by hoothin** [comment]
这边改动太大了，没有好的样式参考之前暂时不打算改。
类别和站点是相反的对比色，而工具栏底色又需要突出类别。
我之前试过，看起来太像讣告了，现在设置页"导出设置"里那个自定义 css 的 light 就是我之前的尝试。
你如果有好的样式参考可以贴上来。

**Comment by wordpure** [comment]
你看看这样行不？

![图片](https://user-images.githubusercontent.com/68013962/199271366-4ce8d8ae-1d21-4fac-8347-eeb42d79308f.png)

![图片](https://user-images.githubusercontent.com/68013962/199271379-faa037b8-6f17-460f-a9bb-9964914f8869.png)

![图片](https://user-images.githubusercontent.com/68013962/199271394-0d063e7f-b42c-4ba7-bb57-4ed12239b3eb.png)

```css
		/* 站点列表 */
		#search-jumper .sitelist > .sitelistCon > p {
			background-color: #252B32 !important;
		}

		#search-jumper .sitelist > .sitelistCon {
			background-color: #1C2127 !important;
		}

		#search-jumper .sitelist > .sitelistCon > div:hover {
			background-color: #283C57 !important;
		}

		#search-jumper .sitelist > .sitelistCon > p,
		#search-jumper .sitelist a > p {
			color: #DADADA !important;
		}

		/* 历史列表 */
		.search-jumper-historylist {
			background-color: #181C20 !important;
		}

		a.search-jumper-word,
		a.search-jumper-word > span {
			background-color: #292A2D !important;
		}

		.search-jumper-tips {
			background-color: #3F4042 !important;
		}

		a.search-jumper-word > span,
		.search-jumper-tips {
			color: #DADADA !important;
		}

		.search-jumper-word:hover {
			text-shadow: 0px 0px 5px #2374FF !important;
		}

		/* 类别 */
		.search-jumper-type,
		.search-jumper-logo {
			background-color: #181C20 !important;
		}
```
